- name: variables from files
  hosts: localhost
  vars_files:
  - varibales.yaml
  tasks:
  - name: printing varibales
    ansible.builtin.debug:
      msg: "We are lerning {{NAME}}, Duration is {{ DURATION}}, Trainer is {{TRAINER}}"