- name: variables at task level
  hosts: localhost
  vars:
  - money: "1000000rs"
    land: "100hectars"
  tasks:
  - name: Inherit values from playbook
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: Inherit values from play and add values
    vars:
    - money: "2000000rs"
      houses: "3 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"