- name: varibales from Inventory
  hosts: mongodb
  tasks:
  - name: print mongodb username
    ansible.builtin.debug:
      msg: "Username is: {{MONGO_USERNAME}}" # this username is defined in inventory file
      
